### ISSUE TITLE
ATH V2.0.0 Overview and Display data issues + Clover showing as "Apple UEFI"

### ISSUE THREAD

**Issue by matxpa** [0xCUB3/About-This-Hack#98] opened 2024-06-30 17:10 UTC
@0xCUB3 

Hi.

On screenshots, your release V2.0.0 is on the right, and my beta on the left

Hard : Laptop Dell Latitude 3510 (i5-10210U, 16 giga DDR4, Intel UHD 620...) Bootloader : Clover r5160

On Overview window :
1) Succinct data on Memory and Monitor
2) wrong bootloader data

![Capture d’écran 2024-06-30 à 18 18 51](https://github.com/0xCUB3/About-This-Hack/assets/70573409/50a97ce3-379b-47e0-b659-0c0f3c06a472)
and tooltip needs some line feeds (on V2.0.0)

![Capture d’écran 2024-06-30 à 18 37 14](https://github.com/0xCUB3/About-This-Hack/assets/70573409/a31467d8-2b20-47e7-bedc-913c49de5dce)

On Display window : 
1) wrong model icon

![Capture d’écran 2024-06-30 à 18 16 54](https://github.com/0xCUB3/About-This-Hack/assets/70573409/5605b1a4-6dfc-4cfe-8781-ba55482987cb)

![Capture d’écran 2024-06-30 à 18 17 13](https://github.com/0xCUB3/About-This-Hack/assets/70573409/8a3c2554-8813-4501-9542-d5f5ffa6c366)

And new Settings window

![Capture d’écran 2024-06-30 à 18 17 45](https://github.com/0xCUB3/About-This-Hack/assets/70573409/a296b693-4fa2-46b1-a7c8-c2696becebd6)

and two ways to show tooltips when detail content is truncated

Cursor on detail content
![Capture d’écran 2024-06-30 à 19 01 13](https://github.com/0xCUB3/About-This-Hack/assets/70573409/035d7fc7-b4ef-4dc8-a248-0f2731ba8620)

Cursor on head line content
![Capture d’écran 2024-06-30 à 19 01 29](https://github.com/0xCUB3/About-This-Hack/assets/70573409/4ed1668a-194e-4f93-94e6-ed585ec48b1c)

Regards

**Comment by 0xCUB3** [comment] 2024-06-30 17:45
Hello matxpa, thank you for reaching out. The reason I haven't implemented the features in your beta is because it increases the clutter in the app. The settings are nice, but a bit overkill for such a simple app, and I want most of the fine details (like clover version) to be only in the tooltip. 

As for the display issue, I added code to make it so that "unknown" displays would just have the default LCD panel show up, as some users had issues with it showing laptop screens even if they were using external monitors because macOS would mistakenly call them "built-in".

To be honest, I haven't looked into the fine details of your beta too much, but I will take a look and see what I might want to include. 

P.S. looks like the "moniteurs" text isn't centered in French. Something to fix for next release!

**Comment by matxpa** [comment] 2024-06-30 18:20
@0xCUB3 
I forget to tell you that this beta uses NO more data files.

**Comment by 0xCUB3** [comment] 2024-06-30 18:21
it's not about data files - it's about a cluttered view. The app goes for minimalism, which your beta starts to discard.

**Comment by matxpa** [comment] 2024-06-30 18:23
ha, ok succinct vs cluttered

**Comment by 0xCUB3** [comment] 2024-06-30 18:25
yep exactly! I love some of the things you put into your beta, but I still haven't decided what/how to implement it :)

**Comment by matxpa** [comment] 2024-06-30 18:29
but a bootloader displaying "Apple UEFI" instead of "Clover ..." remains an issue

**Comment by 0xCUB3** [comment] 2024-06-30 18:30
I'm not sure why that's happening. I don't have a clover mac, so you'd have to debug that one.

**Comment by matxpa** [comment] 2024-06-30 18:32
It worked fine before V2.0.0, someone introduces a bug, not me.

**Comment by 0xCUB3** [comment] 2024-06-30 18:33
I rewrote a lot of the code to be swift native rather than relying on shell commands. Everything else is working fine, but since I don't have a Clover machine to test, I never could confirm if clover still works...

to be fair, you are probably one of maybe 3 people who still use clover 🤣

**Comment by matxpa** [comment] 2024-06-30 18:40
And if I should be the last one i'll be the only one

**Comment by perez987** [comment] 2024-06-30 22:44
@matxpa 
Good night, can I try your beta version?

@0xCUB3 
I can confirm boot loader wrong info (`Apple UEFI` having OpenCore). Maybe last statement 
```swift
      else {
            return "Apple UEFI"
        }
```
always is run at the end of these blocks.

Apart from this, the new version 2 is a great job. Very "swifted".

**Comment by perez987** [comment] 2024-07-01 09:08
@0xCUB3 @matxpa 
`c578f89` is the latest build showing right boot loader info.
After that, "Minimize use of shell commands in all sections" `f049cc2` changes shell commands to swift and HCBootloader.swift shows wrong boot loader info.

**Comment by 0xCUB3** [comment] 2024-07-03 12:25
Issue has been fixed in the latest commit.

**Closed by 0xCUB3** 2024-07-03 12:25 UTC

**Comment by perez987** [comment] 2024-07-03 12:27
@0xCUB3 @matxpa 
b50635a fixes the wrong bootlader info. Tried on OpenCore.
It's a step back but, until the swift code works well on this part, at least the issue has been fixed.
