### ISSUE TITLE
Tooltip displays have extra lines, other tooltips do not (version 2.0.0)

### ISSUE THREAD

**Issue by perez987** [0xCUB3/About-This-Hack#100] opened 2024-07-01 09:43 UTC
Good morning, displays tooltip breaks the appearance of the rest of tooltips.
They all have consecutive lines of info but tooltip displays have blank lines between the lines of info.
I suppose that `!$0.isEmpty` should remove the extra lines (I'm not sure if this is their purpose):
`.prefix { !$0.isEmpty && !$0.hasPrefix("Memory") }`
Can it be set to look as the rest of tooltips?

E.g. displays tooltip:

<img width="378" alt="Displays" src="https://github.com/0xCUB3/About-This-Hack/assets/50429399/85631794-22e7-48c6-b0f2-8a6c3bfc283f"><br>

E.g. other tooltips:

<img width="425" alt="GPU" src="https://github.com/0xCUB3/About-This-Hack/assets/50429399/f846a70a-a428-46e9-a644-1ba8cba4efd7"><br>

Thanks for your work.

**Comment by 0xCUB3** [comment] 2024-07-01 12:46
yeah I'm not sure why this is. I'll have to look into why this is randomly happening and perhaps add some code to strip empty lines.

**Comment by perez987** [comment] 2024-07-02 08:12
@0xCUB3 
Thank you!

**Comment by 0xCUB3** [comment] 2024-07-20 21:08
Sorry for the delay. The issue is fixed in the latest commit:
![CleanShot 2024-07-20 at 17 07 17](https://github.com/user-attachments/assets/90b2ec78-3860-4e6c-b142-49970ccd72f1)

**Closed by 0xCUB3** 2024-07-20 21:08 UTC
